### ISSUE TITLE
Issue-Initial commit

### ISSUE THREAD

**Issue by angel-1x** [angel-1x/p3#2]
Automated Review Comments
Issues in Cargo.toml:
  - (3, 'Hardcoded string found')
Issues in examples/dump-outlines.rs:
  - (11, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in src/otf.rs:
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'TODO found')
  - (50, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (205, 'Line exceeds 80 characters')
  - (207, 'Line exceeds 80 characters')
  - (225, 'Line exceeds 80 characters')
  - (227, 'Line exceeds 80 characters')
  - (228, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (284, 'Line exceeds 80 characters')
Issues in src/util.rs:
  - (12, 'Line exceeds 80 characters')

**Comment by drone-1x** [comment]
I got it.
